### ISSUE TITLE
some problems

### ISSUE THREAD

**Issue by Mayaman5566** [CuriousYoda/tiktok-downloader#2]
Hi,

I use in the cmd
the program works until it asks me to enter the number of tiktoks to download
my python version is 3.9.5
Regards.
![gt](https://user-images.githubusercontent.com/86819296/130354552-1d29bb7c-ff48-4a0c-97c6-c1c9cdcbf08d.jpg)

**Comment by CuriousYoda** [comment]
@Mayaman5566 
Check now. 
Please follow the README properly.

**Comment by Mayaman5566** [comment]
＠CuriousYoda
Hi,
earlier problem is solved!
but have new error  

i think this error means that selenium is not launching correctly?
```
tik-tok-scraper.py", line 149, in <module>userPosts = api.byUsername(username, count=videosToDownload)
AttributeError: 'TikTokApi' object has no attribute 'byUsername'
```

**Comment by CuriousYoda** [comment]
@Mayaman5566 can you share the entire log

**Comment by Mayaman5566** [comment]
Sure!
```
C:\Users\Mayaman\Documents\python\tiktok-downloader-main>python tik-tok-scraper.py
Setting up the selenium headless Chrome Driver
Setting up a connection to unofficial TikTokAPI
Setting up the session for requests

Do you wish to download TikToks for a
   1: User or
   2: HashTag
1
Enter the tik tok user name: Tiktok
Enter the number of tiktoks to download: 1
Traceback (most recent call last):
  File "C:\Users\Mayaman\Documents\python\tiktok-downloader-main\tik-tok-scraper.py", line 149, in <module>
    userPosts = api.byUsername(username, count=videosToDownload)
AttributeError: 'TikTokApi' object has no attribute 'byUsername'
```

**Comment by CuriousYoda** [comment]
@Mayaman5566 It could be the case that test end points are not accessible in your setup.
I made it optional to use_test_endpoints. 

Please do a git pull and try again

**Comment by Mayaman5566** [comment]
The problem still exists, the error message is same :cry:
```
C:\Users\Mayaman\Documents\python\tiktok-downloader-main>python tik-tok-scraper.py
Setting up the selenium headless Chrome Driver
Setting up a connection to unofficial TikTokAPI
Setting up the session for requests

Do you wish to download TikToks for a
   1: User or
   2: HashTag
1
Enter the tik tok user name: Tiktok
Enter the number of tiktoks to download: 5
Traceback (most recent call last):
  File "C:\Users\Mayaman\Documents\python\tiktok-downloader-main\tik-tok-scraper.py", line 162, in <module>
    userPosts = api.byUsername(username, count=videosToDownload)
AttributeError: 'TikTokApi' object has no attribute 'byUsername'
```

**Comment by CuriousYoda** [comment]
Seems the update is not properly applied on your end. 
You should see one extra logging information about test end points. 

![image](https://user-images.githubusercontent.com/86459866/130415756-de2a9242-135f-4166-b01a-8acd601838ac.png)

**Comment by Mayaman5566** [comment]
Because i set VERIFY_FP  :sweat_smile:
now i removed him
```
C:\Users\Mayaman\Documents\python\tiktok-downloader-main>python tik-tok-scraper.py
Setting up the selenium headless Chrome Driver
Setting up a connection to unofficial TikTokAPI
Missing property value: VERIFY_FP
NOT USING TEST END POINTS
Setting up the session for requests

Do you wish to download TikToks for a
   1: User or
   2: HashTag
1
Enter the tik tok user name: Tiktok
Enter the number of tiktoks to download: 1
Traceback (most recent call last):
  File "C:\Users\Mayaman\Documents\python\tiktok-downloader-main\tik-tok-scraper.py", line 162, in <module>
    userPosts = api.byUsername(username, count=videosToDownload)
AttributeError: 'TikTokApi' object has no attribute 'byUsername'
```

**Comment by CuriousYoda** [comment]
@Mayaman5566 Do you have the chromedriver downloaded and added to the folder? I think this was not clear in the documentation. I will update the README

1. Do another git pull.
2. Make sure your chromedriver is in the folder. Download the correct version matching your chrome browser version. 
3. Give it another go

**Comment by CuriousYoda** [comment]
@Mayaman5566 Did it work?

**Comment by Mayaman5566** [comment]
doesn't work
Actually I tried other Tiktok downloader project
Surprisingly, the error codes is same 
I suspect it's my own problem
```
Setting up the selenium headless Chrome Driver
Setting up a connection to unofficial TikTokAPI
Missing property value: VERIFY_FP
Setting up the session for requests

Do you wish to download TikToks for a
   1: User or
   2: HashTag
1
Enter the tik tok user name: Tiktok
Enter the number of tiktoks to download: 1
Traceback (most recent call last):
  File "c:\Users\Mayaman\Documents\python\tiktok-downloader-main\tik-tok-scraper.py", line 163, in <module>
    userPosts = api.byUsername(username, count=videosToDownload)
AttributeError: 'TikTokApi' object has no attribute 'byUsername'
```

**Comment by CuriousYoda** [comment]
@Mayaman5566 My best guess is this is to do with your connection/proxy. Cannot say for sure though

**Comment by CuriousYoda** [comment]
closing as it seems to be a user specific issue
