### ISSUE TITLE
Line 106 in  tik-tok-scraper.py - TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

### ISSUE THREAD

**Issue by rattfieldnz** [CuriousYoda/tiktok-downloader#4]
OS Name: Microsoft Windows 10 Home
Version: 10.0.19044 Build 19044
Google Chrome Version: 104.0.5112.102 (Official Build)  (64-bit)
Chrome Driver Version: ChromeDriver 104.0.5112.79
Powershell Version: 7.2.6
Python Version: 3.10.6

Input Options used:

```
Do you wish to download TikToks for a
   1: User or
   **2: HashTag**
2
Enter the tik tok hashtag: #fortnitelol
Enter the number of tiktoks to download: 5
```

When I execute `python .\tik-tok-scraper.py` in Powershell, with the above inputs, I receive the following error:

```
Downloading TikTok: 6808126703865433350
Traceback (most recent call last):
  File "E:\CloudBackups\OneDrive\tiktok-downloader\tik-tok-scraper-unchanged.py", line 173, in <module>
    downloadPost(
  File "E:\CloudBackups\OneDrive\tiktok-downloader\tik-tok-scraper-unchanged.py", line 147, in downloadPost
    requestAndSaveUrlInChunk(downloadLink, filePath)
  File "E:\CloudBackups\OneDrive\tiktok-downloader\tik-tok-scraper-unchanged.py", line 106, in requestAndSaveUrlInChunk
    total_length = int(response.headers.get('content-length'))
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
```

After looking at some unofficial Python documentation at https://www.geeksforgeeks.org/response-methods-python-requests/,

I made the following change to Line 106 of tik-tok-scraper.py:

From: `total_length = int(response.headers.get('content-length'))`

To: `total_length = int(len(response.content))`

The above change fixed the problem for me - with playable mp4 files being downloaded successfully to the defined location.

I can make a fork and make a pull request if you like. I mainly posted my changes / feedback here  to see if it is an appropriate fix , and not just a 'band-aid' to a problem.
![Capture](https://user-images.githubusercontent.com/2468863/186108185-e73e34a4-1799-4e46-a608-cfd64220a438.PNG)

**Comment by rclakmal** [comment]
Fixed or cannot be reproduced.
